---
title: "Data Visualization with ggplot2"
author: "Julia Sousa"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

```


```{r}

surveys_complete <- read_csv("data/surveys_complete.csv")
surveys_complete

```

```{r}

ggplot(data = surveys_complete)

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()

```




```{r}
# Assign plot to a variable

surveys_plot <- ggplot(data= surveys_complete,
                       mapping = aes(x = weight, y = hindfoot_length))

# Draw the plot

surveys_plot +
  geom_point()

```

# Challenge 1 (optional)

```{r}

install.packages("hexbin")
library("hexbin")

```

```{r}

surveys_plot +
  geom_hex()


# hexagonal strengths: ability to see when there is a higher concentration of coutnts more clearly

# hexagonal weaknesses: points may not be as accurate since they are larger due to their hexagonal shape as opposed to circles, which are smaller, and are able to give more accurate information

```

# Building your plots iteratively

```{r}

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()

```

```{r}

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1)

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, color = "blue")

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, aes(color = species_id))

```

# Challenge 2

```{r}

ggplot(data = surveys_complete, mapping = aes (x = species_id, y = weight)) +
  geom_point(aes(color = plot_type))


# this is a good way to this type of data since you are able to clearly see the plot type for each species

```






