---
title: "Data Visualization with ggplot2"
author: "Julia Sousa"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

```


```{r}

surveys_complete <- read_csv("data/surveys_complete.csv")
surveys_complete

```

```{r}

ggplot(data = surveys_complete)

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()

```




```{r}
# Assign plot to a variable

surveys_plot <- ggplot(data= surveys_complete,
                       mapping = aes(x = weight, y = hindfoot_length))

# Draw the plot

surveys_plot +
  geom_point()

```

# Challenge 1 (optional)

```{r}

install.packages("hexbin")
library("hexbin")

```

```{r}

surveys_plot +
  geom_hex()


# hexagonal strengths: ability to see when there is a higher concentration of coutnts more clearly

# hexagonal weaknesses: points may not be as accurate since they are larger due to their hexagonal shape as opposed to circles, which are smaller, and are able to give more accurate information

```

# Building your plots iteratively

```{r}

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()

```

```{r}

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1)

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, color = "blue")

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, aes(color = species_id))

```

# Challenge 2

```{r}

ggplot(data = surveys_complete, mapping = aes (x = species_id, y = weight)) +
  geom_point(aes(color = plot_type))


# this is a good way to this type of data since you are able to clearly see the plot type for each species

```


# Boxplot

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
  geom_boxplot()

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
  geom_boxplot(alpha = 0) +
  geom_jitter(alpha = 0.3, color = "tomato")
```

# Challenge 3

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
  geom_violin()

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) + 
  scale_y_log10() +
  geom_violin()

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
  geom_boxplot() +
  geom_jitter()

```

```{r}

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
  geom_boxplot() +
  geom_jitter(color = "blue")

```


# Plotting Time Series Data

```{r}

yearly_counts <- surveys_complete %>% 
  count(year, genus)

ggplot(data = yearly_counts, aes(x = year, y = n)) +
  geom_line()

```


```{r}

ggplot(data = yearly_counts, aes(x = year, y = n, group = genus)) +
  geom_line()

```

```{r}

ggplot(data = yearly_counts, aes(x = year, y = n, color = genus)) +
  geom_line()

```

# Integrating the pipe operator with ggplot2

```{r}

yearly_counts %>% 
  ggplot(mapping = aes(x = year, y = n, color = genus)) +
  geom_line()

```

```{r}

yearly_counts_graph <- surveys_complete %>%
  count(year, genus) %>% 
  ggplot(mapping = aes(x = year, y = n, color = genus)) +
  geom_line()

yearly_counts_graph

```

# Faceting

```{r}

ggplot(data = yearly_counts, aes(x = year, y = n)) +
  geom_line() +
  facet_wrap(facets = vars(genus))

```

```{r}

yearly_sex_counts <- surveys_complete %>% 
  count(year, genus, sex)

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(facets = vars(genus))

```

```{r}

ggplot(data = yearly_sex_counts,
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(rows = vars(sex), cols = vars(genus))

```

```{r}


# One column, facet by rows

ggplot(data = yearly_sex_counts,
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(rows = vars(genus))

```
```{r}

# One row, facet by column

ggplot(data = yearly_sex_counts,
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(cols = vars(genus))

```

# ggplot2 Themes

```{r}

ggplot(data = yearly_sex_counts,
       mapping = aes(x = year, y = n, color = sex)) + 
  geom_line() +
  facet_wrap(vars(genus)) +
  theme_bw()

```

```{r}

yearly_weight <- surveys_complete %>%
  group_by(year, species_id) %>% 
  summarize(avg_weight = mean(weight))

ggplot(data = yearly_weight, mapping = aes(x = year, y = avg_weight)) +
  geom_line() +
  facet_wrap(vars(species_id)) +
  theme_bw()

```

# Customization

```{r}

ggplot(data = yearly_sex_counts, aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(vars(genus)) +
  labs(title = "Observed genera through time",
       x = "Year of observation",
       y = "Number of individuals") +
  theme_bw()

```

```{r}

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(vars(genus)) +
  labs(title = "Observations through time",
       x = "Years of observation",
       y = "Number of individuals") +
  theme_bw() +
  theme(text=element_text(size = 16))

```

```{r}

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(vars(genus)) +
  labs(title = "Observed genera through time",
       x = "Years of observation",
       y = "Number of individuals") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                      axis.text.y = element_text(colour = "grey20", size = 12),
                      strip.text = element_text(face = "italic"),
                      text = element_text(size = 16))

```

```{r}

grey_theme <- theme(axis.text.x = element_text(colour = "grey20", size = 12,
              angle = 90, hjust = 0.5,
              vjust = 0.5),
                    axis.text.y = element_text(colour = "grey20", size = 12),
              text = element_text(size = 16))

ggplot(surveys_complete, aes(x = species_id, y = hindfoot_length)) +
  geom_boxplot() +
  grey_theme

```

# Challenge 4

```{r}



```









