---
title: "Lab 4: Data wrangling and graphing COVID-19 reporting data (Part I)"
author: "Julia Sousa"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

```


```{r}

report_03_11_2020 <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv") %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State")

str(report_03_11_2020)

```

```{r}
view(report_03_11_2020)

```


```{r}

library(DT)
datatable(report_03_11_2020)

```


# Exercises (Part 1)

```{r}

report_03_13_2020 <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv") %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State")

str(report_03_13_2020)

view(report_03_13_2020)

```

```{r}

report_09_13_2020 <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")

str(report_09_13_2020)

view(report_09_13_2020)

```


```{r}

report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(total_counts = n())

view(report_09_13_2020)

```


```{r}

report_09_13_2020 %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed = sum(Confirmed))

```


```{r}

report_09_13_2020 %>%
  group_by(Country_Region) %>% 
  summarize(Total_Deaths = sum(Deaths)) %>% 
  arrange(desc(Total_Deaths)) %>% 
  slice(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
  
  
```



# Exercises (Part 2)

```{r}
# Top 10 countries with the most deaths on 3/13/2020 using a scatter plot and bar graph

Top10Deaths <- report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice_max(Deaths, n= 10)

```

```{r}

ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) + 
  geom_point()


ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_bar(stat = 'identity')

```


```{r}

# Top 10 countries with the most confirmed cases on 3/13/2020 using a scatter plot and bar graph

Top10Confirmed <- report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  arrange(desc(Confirmed)) %>% 
  slice_max(Confirmed, n= 10)

```


```{r}

ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_point()


ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_bar(stat = 'identity')

```


```{r}

# Top 10 Counties with most deaths on 9/13/2020 using a scatter plot and bar graph

Top10Deaths <- report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice_max(Deaths, n= 10)

```


```{r}

ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_point()


ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_bar(stat = 'identity')

```




```{r}

# Top 10 countries with the most confirmed cases on 9/13/2020 using a scatter plot

Top10Confirmed <- report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  arrange(desc(Confirmed)) %>% 
  slice_max(Confirmed, n= 10)

```


```{r}

ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_point()


ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_bar(stat = 'identity')

```



