---
title: "Lab 9x"
author: "Julia Sousa"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

```



## Conditional statements if-else

```{r}

x <- runif(1, 0, 10)
if(x > 3) {
  y <- 10
} else {
  y <- 0
}


```


## For loops

```{r}

for(i in 1:10) {
        print(i)
}

```

```{r}

x <- c("a", "b", "c", "d")
for(i in 1:4) {
        print(x[i])
}

```

```{r}

for(i in seq_along(x)) {   
        print(x[i])
}

```

```{r}

for(letter in x) {
        print(letter)
}

```

```{r}

for(i in 1:4) print(x[i])

```


## Nested for loops

```{r}

x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
          for(j in seq_len(ncol(x))) {
                  print(x[i, j])
          }
}

```

## while Loops

```{r}

count <- 0
while(count < 10) {
          print(count)
          count <- count + 1
}

```

```{r}

z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
          coin <- rbinom(1, 1, 0.5)
          
          if(coin == 1) {
                  z <- z + 1
          } else {
                  z <- z - 1
          }
          
}
print(z)

```

## Your first function

```{r}

f <- function() {
  
}
class(f)

```

```{r}

f()

```

```{r}

f <- function () {
        cat("Hello, world!\n")
}
f()

```

```{r}

f <- function(num) {
        for(i in seq_len(num)) {
                cat("Hello, world!\n")
        }
}
f(3)

```

```{r}

f <- function(num) {
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(3)

```

```{r}

print(meaningoflife)

```

```{r}

f <- function(num = 1) {
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()

```

```{r}

f(2)

```

```{r}

f(num = 2)

```


## Exercises

#Conditional statements with if-else

```{r}

x <- runif(1, 7, 13)
if(x > 5) {
  y <- 9
} else {
  y <- 2
}

```


#For loops


```{r}

for(i in 5:15) {
        print(i)
}

```

```{r}

x <- c("x", "y", "z")
for(i in 1:3) {
        print(x[i])
}

```

```{r}

for(i in seq_along(x)) {
        print(x[i])
}

```

```{r}

for(letter in x) {
          print(letter)
}

```
```{r}

for(i in 1:3) print(x[i])


```

#Nested for loops

```{r}

x <- matrix(1:10, 2, 5)
for(i in seq_len(nrow(x))) {
          for(j in seq_len(ncol(x))) {
                    print(x[i, i])
          }
}

```

#while Loops

```{r}

count <- 3
while(count < 10) {
          print(count)
          count <- count +1
}

```

```{r}

z <- 7
set.seed(1)
while(z >= 4 && z <= 13) {
          coin <- rbinom(1, 2, 0.5)
          
          if(coin == 2) {
                  z <- z + 1
          } else {
                  z <- z - 1
          }
}
print(z)

```


#Your first function

```{r}

f <- function() {
  
}
class(f)

```

```{r}

f()

```

```{r}

f <- function() {
        cat("Happy Thanksgiving!\n")
}
f()

```

```{r}

f <- function(num) {
          for(i in seq_len(num)) {
                  cat("Happy Thanksgiving!\n")
          }
}
f(2)

```

```{r}

f <- function(num) {
          happy <- "Happy Thanksgiving!\n"
          for(i in seq_len(num)) {
                    cat(happy)
          }
          chars <- nchar(happy) * num
          chars
}
happyholidays <- f(5)

```

```{r}

print(happyholidays)

```

```{r}

f <- function(num = 2) {
          happy <- "Happy Thanksgiving!\n"
          for(i in seq_len(num)) {
                  cat(happy)
          }
          chars <- nchar(happy) * num
          chars
}
f()

```

```{r}

f(3)

```

```{r}

f(num = 3)

```







